### ISSUE TITLE
File Upload Mechanism

### ISSUE THREAD

**Issue by akshaykokane** [ReneRanzinger/IFEDS-backend#10]

**Comment by Anubhav2201** [comment]
Similar ticket was open on frontend as well.
Link: https://github.com/ReneRanzinger/IFEDS-frontend/issues/16

**Status as on December 12,2019 for frontend ticket:** 
Discussed with Sanath. We will be using ReactResumableJS component https://github.com/Artear/ReactResumableJS for file upload.

Closing this ticket
