### ISSUE TITLE
Is public dataset service being change from /getDatasets to /datasets ?

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#21]
On Updating backend code, /getDatasets service did not work .
Going through backend code it has been modified to /datasets.
Please confirm.

**Comment by susgeorge** [comment]
Yes!
I had a ticket for it.

- Changed the view datasets endpoint from /getDatasets to /datasets
- Changed the dataset details service endpoint from ?datasetId= to /dataset/{datasetId}

**Comment by Anubhav2201** [comment]
Thank you @susgeorge
