### ISSUE TITLE
Getting status code 500 when token expires for /dataset endpoint

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#23]
- While testing for expire token, I am getting 500 status code with message ExpiredJwtException error message. Should this be better handled or this is the correct way to handle this endpoint with JWT Token Expired ?

**Comment by akshaykokane** [comment]
- I guess this is the correct approach. When you get the message of TokenExperies, redirect the user to login page

**Comment by akshaykokane** [comment]
Let me know if you want to change the type of message or if you have any suggestions on it. Else feel free to close the ticket. Thanks

**Comment by susgeorge** [comment]
On token expiration,the end-point gives a error json. In the front end,using the error code and message ,the user needs to be redirected to login page
