### ISSUE TITLE
Service not present for getting details of particular Sample to Display on Edit Sample form

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#32]
- I can pass the sample data from the Sample List Table to edit Sample Form but will not be able to display all the sample descriptor associated with it as a field value to edit.
- There should be a service for getting details of particular sample along with the sample descriptor associated with it.

**Comment by akshaykokane** [comment]
- Need to work on this web service

So for clarification:

- You need a service that will display all sample descriptors associated with a particular sample.

Two ways to create it : 

**/getSample/{sampleId}** -> will return all information about samples as well as sample descriptors ( we already have this service, but we don't return sample descriptors in it)

**/getSampleDescriptors/{sampleId}** -> will return only sample descriptors associated with sample

@ReneRanzinger  could you please help in deciding on how this web service should be?

**Comment by ReneRanzinger** [comment]
@akshaykokane Just one service to get the sample including its descriptors. Similar to the the save service it should get sample and discriptors in one JSON.

**Comment by akshaykokane** [comment]
b400d0a

**Comment by akshaykokane** [comment]
Completed : 
/getSamples service returns only the list of owned samples.

WIP : samples/{sample_id} :
return all information about particular sample

**Comment by akshaykokane** [comment]
53753645eae5e978a2ea1276c7741f7f29431775

https://documenter.getpostman.com/view/8476939/SW7T7Wqv?version=latest#5304a2a8-feb1-49db-8af0-9306063598ed
