### ISSUE TITLE
Implement File Upload WebService

### ISSUE THREAD

**Issue by akshaykokane** [ReneRanzinger/IFEDS-backend#38]
WIP:

5dbc50ae3bfdd06f04baee789cfdf85643f1c426

**Comment by akshaykokane** [comment]
fe20caec2e49b4e1c57c64f9367bfd29b9e2de36

**Comment by akshaykokane** [comment]
WIP

**Comment by akshaykokane** [comment]
- Need clarification on data_file and data_type. 
What is data_type? And will data_type will be given in dropdown while uploading the data_file?
- Dataset can have single or multiple data_files? 
Not sure that dataset and data_files should have one-one relationships or one-many?
- What can be a file type?
[pdfs, xlsx, docs]
- What should be mangled file_name?
I decided to have [timestamp_dataset_id], any other suggestion?
- Deleting the dataset should also delete the physical file from the system. Haven't handled this in delete dataset webservice.

@ReneRanzinger could you please help me with these doubts? Thanks

**Comment by ReneRanzinger** [comment]
**Data Type**
The data type describes kind of file that was uploaded (not the extension). Examples are "Mass spec raw data", "mzXML", "image" etc.

**Data file**
Each dataset can have many data files. Each file can only be part of one dataset.

**File type**
If you are asking because of the upload. There is no limit in file type. We also will not do any validation for now.

**File name**
Seems redundant. Files that come first have the lower ID, files that come later have the higher ID. Any reason ID alone is not sufficient?

**Comment by akshaykokane** [comment]
@ReneRanzinger 

**Data Type**
- Okay, so datatype will be accepted from the user while uploading the file. Or will the data types predefine?

**Data file**
- I guess then we missed to create a m-n mapping table. dataset_to_datafile

**File Type**
- Got it

**Filename**
- Ahh. Sorry, my bad. I didn't think of autoincrement id. Thanks

**Comment by akshaykokane** [comment]
@Anubhav2201 so agreeing upon the input from front-end
The backend will expect the following parameters:
- resumableFilename
- resumableChunkSize
- resumableChunkNumber
- resumableTotalChunks
- dataset_id
- data_type_id
- description

Please correct me if I am wrong. Thank you!

**Comment by ReneRanzinger** [comment]
**Data File**
No need for m--to-n its 1-m. the current database should be just fine.

**Data type**
Predefined. Its one of the dictionaries (like keyword).

**Comment by akshaykokane** [comment]
@ReneRanzinger 
Ohh sorry. I got you. Thank you for clarification.

**Comment by akshaykokane** [comment]
WIP : 597f17a1e4d26fcc8a1fc0c29b506a8f0a2f27e2

**Comment by akshaykokane** [comment]
WIP : 28ef4adc79152dcfa3640ec4782b96c3f0ad0cbc

Updated SQL DUMP

**Comment by akshaykokane** [comment]
WIP: a4c959ab59bfe9386cd6b97112b5249783cc4df5

Made Dataset_id in data_file nullable

**Comment by akshaykokane** [comment]
-updated schema and insert query

6740c1cd71b71e29b963ad3ceacb89fc1e19554c

@Anubhav2201 
Please update Database schema - ifed_core.sql
Please update insert data - insert_core.sql

Let me know if it causes any issue at front end

**Comment by akshaykokane** [comment]
93c8c7880567b00e3a55f2db4924ff7e416f36ee

**Comment by akshaykokane** [comment]
c3a3b2f9856047b5b946861626818766320222f0

eb9bf50a0839aed305a4ea179c9457888eaffe5e
