### ISSUE TITLE
Cross-origin

### ISSUE THREAD

**Issue by akshaykokane** [ReneRanzinger/IFEDS-backend#50]

**Comment by akshaykokane** [comment]
d53b7f73b3b09ad1b93528b37bb5b0c05d65017b

@Anubhav2201 Please check if the CORS  issue is now resolved.

**Comment by Anubhav2201** [comment]
@akshaykokane I am still facing same issue

**Comment by akshaykokane** [comment]
a3564ca5a8231db2123e5f1ed5e1f881272b60bd

**Comment by Anubhav2201** [comment]
@akshaykokane Thank you for the cors changes. Things are working now.
You can close the issue.
