### ISSUE TITLE
Edit Sample Service Not Working

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#52]
@akshaykokane Can you please take a look ?

**Comment by akshaykokane** [comment]
Taking a look! @Anubhav2201

**Comment by akshaykokane** [comment]
it's working at my end. Could you share the error message?

**Comment by akshaykokane** [comment]
@Anubhav2201 please confirm if its working. If not, please repoen the issue with more error details/screenshot
