### ISSUE TITLE
Settings table

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#54]
- Create a settings table to store key value pairs
-- primary key (Serial)
-- key (string)
-- value (string)
- add two rows
1. "header.name" -> "IFEDS"
2. "header.logo" -> "https://pngimage.net/wp-content/uploads/2018/06/logo-placeholder-png-2.png"

**Comment by akshaykokane** [comment]
6ab805bbbd23ff52df510c043bae08152f7772f6

**Comment by akshaykokane** [comment]
e2388e6ccc1a7398433a4d299d8be735ee8539b6
