### ISSUE TITLE
Application init WS

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#55]
Get service with no parameter to retrieve application specific settings in JSON format. In first instance these are the header name and header logo.

**Comment by akshaykokane** [comment]
Example Output:
```
[
    {
        "key": "header.logo",
        "value": "1.jpg"
    },
    {
        "key": "header.text",
        "value": "Hello"
    },
    {
        "key": "header.subTitle",
        "value": "HelloWorld"
    }
]
```


116224862696c523ad201e88a19934df54b09e1c
