### ISSUE TITLE
Password reset WS 1

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#56]
**Input:** 
- user name or email

**Function:**
- check if user name or email is valid otherwise return error
- get email and generate a token for this user (needs to be store in database, either as column in user table or as separate table)
- send email with the token and a link to the reset page
- return success

**Return:** 
- error if user name or email is incorrect
- success message if email was send

**Comment by akshaykokane** [comment]
EMAIL EXAMPLE

<img width="633" alt="Screenshot 2020-04-18 at 1 51 02 AM" src="https://user-images.githubusercontent.com/30575487/79629366-33b5ba00-8117-11ea-90da-9c25088e6e52.png">


GET `localhost:8080/reset_password/{username or email}`

Response JSON:
```
{
	 message : success
}
```

**UPDATED**: the password reset link is been updated  
to `glygen.ccrc.uga.edu/ifeds/password_reset/{token}`

**Comment by akshaykokane** [comment]
Issue: Any Expiry?

**Comment by akshaykokane** [comment]
For production: 

1. Need to change

In Application.properties at line 28, 29

spring.mail.username=username@gmail.com
spring.mail.password=password


2. In providerController change the password_reset_url

**Comment by akshaykokane** [comment]
494f4cb62eade09eddf83ade8b63612c8cf09d54
