### ISSUE TITLE
Password reset WS 2

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#57]
**Input**
- Token
- new password

**Function**
- Check if that is a valid password reset token => else error
- Invalidate token
- check password => else error
- save password
- success

**Ouput**
Error json or success json.

**Comment by akshaykokane** [comment]
- check if the content in the password Column is 'RESET {token}'
- if yes, then split string by whitespace
- match the token
- if token matched, then change the password
