### ISSUE TITLE
User permission level

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#58]
1. Create a permission table 
- primery key (serial)
- foreign key (provider table)
- permission level (string)

2. Add permission level "admin" to one of the users

3. When user logs in the permission level need to be transfered to client.

**Comment by akshaykokane** [comment]
6e783e5

**Comment by akshaykokane** [comment]
CREATE permissions TABLE : 6e783e5fd6faaced07af14cc4b11c802f65c742c

INSERT permissions TABLE : 79635028fd450e996cd46d56f16fd2d63a6ad6ba

**Comment by akshaykokane** [comment]
```
{
    "permission_level": "admin",
    "token": "abcdefghijklmnopqurstuvmxyz"
}
```

**Comment by akshaykokane** [comment]
3c8c3eda75d066032ec16273e3ee0d9d64dc6ab9
