### ISSUE TITLE
Get user permission Ws

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#63]
**Input**
- Token

**Function**
- Check if token belongs to admin => error
- Get all users (except current user): username, email, admin, user id
- success

**Ouput**
Error json or user list json.

**Comment by akshaykokane** [comment]
If admin -> then returns the permissions

Doesn't return the permission of current user (Admin)

```
[
    {
        "username": "ccrc_user2",
        "email": "ccrc2@gmail.com",
        "provider_id": 4,
        "permission_level": "client"
    }
]
```

**Comment by akshaykokane** [comment]
6c18f49f1c250058a3f12d8e79d340afa5072cf2
