### ISSUE TITLE
Update user permission WS

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#64]
**Input**
- Token
- User ID
- Action (promote, demote, disable, enable)

**Function**
- Check if token belongs to admin => error
- Check user ID => error
- Make sure that at least one active admin remains
- Admin account can not be disabled
- save 
- success

**Ouput**
Error json or success json.

**Comment by akshaykokane** [comment]
6c18f49f1c250058a3f12d8e79d340afa5072cf2

**Comment by akshaykokane** [comment]
`/permissions/{action}/{id}`
Updates Permissions of user

**Comment by akshaykokane** [comment]
- error (this is not allowed operation)

**Comment by akshaykokane** [comment]
- disabled cannot log in
- disable -> update flag in provider table
- promote/dempte -> on permission table

**Comment by akshaykokane** [comment]
b326c26d0990742dfb7afc4ff1cfaa34d16a46f6

✔ disabled user cannot log in
✔ enable/disable -> updates flag in provider table
✔ promote/demote -> on permission table
