### ISSUE TITLE
Add dictionary entry

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#67]
**Input**
- Token
- dictionary
- new entry

**Function**
- Check if token belongs to admin => error
- Validate entry => error
- save new entry
- success

**Ouput**
Error json or success json.

**Comment by akshaykokane** [comment]
## **Funding Source:**

`localhost:8080/dictionary/funding_source`

Sample Input JSON:

```
{
	 "name": "funding_src_sample",
	 "url": "test.com",
	 "abbreviation":"FSS"
	
}
```

## **Keywords:**
localhost:8080/dictionary/keywords

Sample Input JSON:

```
{
	 "name": "keywords sample",
	 "url": "test.com",
	 "description":"hello world"
	
}
```

## **Sample Descriptors:**
localhost:8080/dictionary/keywords

Sample Input JSON:

```
{
	 "name": "keywords sample",
	 "url": "test.com",
	 "namespace":"hello",
	 "link_pattern":"null",
	 "description":"hello world"
	
}
```

Sample Output:

```
{
	 message: success
}
```

**Comment by akshaykokane** [comment]
445adb324b0776b5436797e3e571059e77a3068d

**Comment by akshaykokane** [comment]
5bdb2234196248e420303fc7f32d5b2ae3c25f2d

added

## **Experiment Type**

Sample Input:

```
{
	 "name": "keywords sample",
	 "url": "test.com",
	 "description":"hello world"
	
}
```
