### ISSUE TITLE
Delete dictionary entry

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-backend#68]
**Input**
- Token
- dictionary
- entry id

**Function**
- Check if token belongs to admin => error
- Check dictionary and entry ID => error
- Check if entry is unused => error
- remove entry
- success

**Ouput**
Error json or success json.

**Comment by akshaykokane** [comment]
445adb324b0776b5436797e3e571059e77a3068d

**Comment by akshaykokane** [comment]
5bdb2234196248e420303fc7f32d5b2ae3c25f2d
`
DELETE localhost:8080/dictionary/experiment_type/1`
