### ISSUE TITLE
Dashboard Web Service

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#69]
Input
 - the login token (not json , it will be in the header)

Output
 - a json with number of sample and dataset

**Comment by akshaykokane** [comment]
e076f5c0387fac3c09ec31f691e10f3da931f00d

```
{
    "num_of_samples": 50,
    "num_of_dataset": 1
}
```

**Comment by akshaykokane** [comment]
`localhost:8080/dashboard/`

**Comment by akshaykokane** [comment]
@Anubhav2201

**Comment by akshaykokane** [comment]
fa992a13bca2b1e8ce84257dc7d3d72e642af7d0
