### ISSUE TITLE
Getting 400 status code on Add Sample and Add Dataset web service

### ISSUE THREAD

**Issue by akshaykokane** [ReneRanzinger/IFEDS-backend#81]
I am getting an error in adding  dataset and sample. These are my Post requests. So can you please check with following json whether these json are currently executing at your end.

**Comment by Anubhav2201** [comment]
Following is the json payload I am sending to add dataset service:

{"datasetName":"Test","description":"This is for test purpose","experiment_types":[{"experiment_type_id":1,"description":"This is for test purpose"},{"experiment_type_id":2,"description":"This is for test purpose"}],"funding_grant":[{"funding_source_id":1,"grant_number":"2345","url":"https://glygen.ccrc.uga.edu/ifeds/adddataset"},{"funding_source_id":2,"grant_number":"23456","url":"https://glygen.ccrc.uga.edu/ifeds/adddataset"}],"is_public":true,"keywordsIds":[1],"paperIds":[12345],"sampleIds":1}

**Comment by Anubhav2201** [comment]
Following is the json payload for adding sample:

{"name":"Test","sample_type_id":2,"url":"https://glygen.ccrc.uga.edu/ifeds/addsample","description":"This is for test purpose","sample_descriptors":[{"sample_descriptor_id":1,"sample_descriptor_value":"Test","unit_of_measurment":"Random"},{"sample_descriptor_id":3,"sample_descriptor_value":"Test1","unit_of_measurment":"Random1"}]}

**Comment by akshaykokane** [comment]
Resolved 400 status code on Add new Dataset : 5711719cd912db501070cb2a98821d3b7650be8e

**Comment by akshaykokane** [comment]
Resolved for Add new Sample: 70bb5d11ee2643f602429bf82b43a38abaacbec7

No major changes, everything seems to be working fine. Please make sure that sample descriptors exist in the database. 

I used same payload and didn't get error

If no error, then please close the ticket

@Anubhav2201

**Comment by akshaykokane** [comment]
618452615ab64a4a552af97c33bfeff98098616e

**Comment by akshaykokane** [comment]
Also make sure that in add dataset, paper exists in the database

https://glygen.ccrc.uga.edu/ifeds/api/paper_mata_data/1

**Comment by akshaykokane** [comment]
a0339a82782b4df504f0eda956abaa454cecccbf

**Comment by akshaykokane** [comment]
@Anubhav2201 Everything is working now. Please check once
