### ISSUE TITLE
User Permission web service /permissions is currently not providing any users details

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#84]
- Not enough users to provide details
- No way to determine is the user is disabled user or not

**Comment by akshaykokane** [comment]
WIP

**Comment by akshaykokane** [comment]
Patched to show all users and its permissions: c19689cc6d40a83a0f4fccb38c663bea91001369

**Comment by akshaykokane** [comment]
22e9033e82a079a8daad4f83373ab7249bb9deb6
