### ISSUE TITLE
update_provider web service is not updating user information on database.

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#91]
Update User Service is working fine with 200 as status but not giving any success or error response. And While calling Back getProvider web service, updated information is not provided. Likely update user service is not updating information on database. If Username is updated, then changes are reflected on Database

**Comment by akshaykokane** [comment]
Getting following response on server

![image](https://user-images.githubusercontent.com/30575487/82741556-52fcc400-9d21-11ea-994d-ba1353b8bbbb.png)

And information is getting updated at the backend

<img width="1092" alt="Screenshot 2020-05-23 at 6 16 14 PM" src="https://user-images.githubusercontent.com/30575487/82741577-abcc5c80-9d21-11ea-9c0e-184fc7bcc8af.png">

**Comment by Anubhav2201** [comment]
Can you please test with url or description update

**Comment by akshaykokane** [comment]
1ef545b1edc724d10523573053730495dc7c2c70

**Comment by akshaykokane** [comment]
34f9f6c5ab4f776b7ae2da48fb5abd1a878faf59

**Comment by akshaykokane** [comment]
<img width="497" alt="Screenshot 2020-05-30 at 10 16 23 PM" src="https://user-images.githubusercontent.com/30575487/83343000-3fbe9b00-a2c3-11ea-82e3-00821f9b54e1.png">

**Comment by akshaykokane** [comment]
18adb518adca0271510f715a319e0e4e70b7ee56
